**Домашнее задание**

In [4]:
import pandas as pd

**Задание 1**

Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
	- оценка 2 и меньше - низкий рейтинг
	- оценка 4 и меньше - средний рейтинг
	- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [3]:
ratings = pd.read_csv('ml-latest-small/ratings.csv')

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [8]:
def class_(param):
    if param <= 2.0:
        class_ = 'low'
    elif 2.0 < param <= 4.0:
        class_ = 'medium'
    elif 4.5 <= param <= 5.0:
        class_ = 'high'
    return class_

In [13]:
ratings['class'] = ratings['rating'].apply(class_)
ratings.head()

   userId  movieId  rating  timestamp   class
0       1        1     4.0  964982703  medium
1       1        3     4.0  964981247  medium
2       1        6     4.0  964982224  medium
3       1       47     5.0  964983815    high
4       1       50     5.0  964982931    high

**Задание 2**

Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

Результат классификации запишите в отдельный столбец region.

In [83]:
keywords = pd.read_table('keywords.csv', sep = ',', encoding = 'utf-8')
keywords.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [84]:
geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

In [104]:
def geo_class(keyword):
    for key, value in geo_data.items():
        for city in value:
            if city in keyword:
                region = str(key)
                break
            else:
                region = 'undefined'
                
    return region

In [105]:
keywords['region'] = keywords['keyword'].apply(geo_class)

In [108]:
keywords[keywords['region'] != 'undefined']

,keyword,shows,region
1063,фарпост владивосток,176951,Дальний Восток
2175,дром хабаровск,98361,Дальний Восток
3206,дром владивосток,73084,Дальний Восток
3275,100 сп владивосток,76418,Дальний Восток
3687,авито хабаровск,63736,Дальний Восток
5858,владивосток,43038,Дальний Восток
6260,фарпост хабаровск,40962,Дальний Восток
8039,погода в хабаровске,33437,Дальний Восток
9084,хабаровск,29655,Дальний Восток
9293,100 сп хабаровск,29475,Дальний Восток
10261,дром хабаровский край,27062,Дальний Восток
14637,презент хабаровск свежий номер,20524,Дальний Восток
16474,работа в хабаровске,18284,Дальний Восток
16544,погода во владивостоке,18262,Дальний Восток
18148,farpost владивосток,16725,Дальний Восток
20332,100сп владивосток совместные покупки,18197,Дальний Восток
20935,форпост во владивостоке,14703,Дальний Восток
21309,работа во владивостоке,14668,Дальний Восток
21406,монастырев интернет магазин владивосток,15108,Дальний Восток
21445,сахалин,14494,Дальний Восток
21883,виндгуру владивосток,14254,Дальний Восток
22393,сайт владивостока,13951,Дальний Восток
22674,новости владивостока,13810,Дальний Восток
22909,погода владивосток,16193,Дальний Восток
23547,южно сахалинск,13386,Дальний Восток
24347,погода во владивостоке на 5 дней,13090,Дальний Восток
24827,монастырев владивосток,12823,Дальний Восток
26175,презент хабаровск,12394,Дальний Восток
26305,100сп владивосток,12172,Дальний Восток
27280,работа 27 в хабаровске свежие вакансии,11967,Дальний Восток
...,...,...,...
62770,аптека миницен хабаровск интернет магазин,5585,Дальний Восток
63549,суперджоб хабаровск,5531,Дальний Восток
64690,проститутки владивосток,5527,Дальний Восток
65122,центр занятости населения хабаровск,5729,Дальний Восток
66155,примпогода г владивосток на 5 дней,5248,Дальний Восток
67136,погода в хабаровске на неделю,5593,Дальний Восток
67307,место происшествия хабаровск,5401,Дальний Восток
68148,хабаровский край,5177,Дальний Восток
68609,автодром владивосток,5446,Дальний Восток
68736,красная икра сеть магазинов ооо сахалинская ры...,5069,Дальний Восток
69360,дром ру владивосток,7239,Дальний Восток
69652,пегас туристик поиск тура из хабаровска,5064,Дальний Восток
69716,программа передач на сегодня владивосток,5277,Дальний Восток
71869,дв хаб официальный сайт хабаровск,4943,Дальний Восток
72019,барахолка владивосток фарпост,6845,Дальний Восток
72430,vl ru владивосток,4896,Дальний Восток
72766,2 гис хабаровск,5180,Дальний Восток
78517,фарпост владивосток вакансии работа,4770,Дальний Восток
80269,телепрограмма на сегодня хабаровск,4762,Дальний Восток
81887,проститутки хабаровска,4337,Дальний Восток
82474,2гис владивосток,4385,Дальний Восток
88430,юла бесплатные объявления хабаровск,4079,Дальний Восток
89445,живодерки из хабаровска,4035,Дальний Восток
89757,аптека на батуевской ветке хабаровск интернет ...,4024,Дальний Восток
89937,расписание электричек владивосток,4212,Дальний Восток
90402,аэропорт владивосток,4658,Дальний Восток
92442,монастырев владивосток официальный сайт,3870,Дальний Восток
92843,проститутки хабаровск,4120,Дальний Восток
93872,биглион хабаровск,3890,Дальний Восток
95572,точное время владивосток,4142,Дальний Восток

**Задание 3 (бонусное)**

Есть мнение, что "раньше снимали настоящее кино, не то что сейчас". Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

1. В переменную years запишите список из всех годов с 1950 по 2010.

2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
	- для каждой строки пройдите по всем годам списка years
	- если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
	- если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год

3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец 'year'

4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца 'year' и отсортируйте результат по убыванию рейтинга

In [3]:
years = []
for year in range(1950,2011):
    years.append(str(year))

In [16]:
ratings = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')

In [17]:
joined = ratings.merge(movies, how='left', on='movieId')
joined.head()

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama

In [24]:
def production_year(title):
    for year in years:
        if str(year) in title:
            year = str(year)
            break
        else:
            year = '1900'
    return year

In [33]:
joined['year'] = joined['title'].apply(production_year)
joined_filtered = joined.filter(items = ['rating', 'year'])
joined_filtered.groupby('year').mean()[['rating']].sort_values('rating', ascending=False).reset_index().head()

   year    rating
0  1957  4.014241
1  1972  4.011136
2  1952  4.000000
3  1954  3.994220
4  1951  3.983539